/********************************************
* VerifWorks Go2UVM App: VW_DVC_Go2UVM
* Automatically generated by VerifWorks's DVC_Go2UVM Riviera Apps 
* Thanks for using VerifWorks products
* Visit http://www.verifworks.com for more 
* Generated on   : 2016-06-04 12:23:32
********************************************/ 



// Generating SystemVerilog interface for module: or_multi
// ---------------------------------------------------------
interface or_multi_if (input logic clk,clk2);
  logic  [0:0] a;
  logic  [0:0] b;
  logic  [0:0] c;
  logic  [0:0] reset_n;
 // logic  [0:0] clk2;
  logic  [0:0] d;
  logic  [0:0] e;
  // End of interface signals 


  // Start of clocking block definition 
  clocking cb @(posedge clk or posedge clk2);
    output a;
    output b;
    output c;
    output reset_n;
   // output clk2;
    output d;
    output e;
  endclocking : cb
  // End of clocking block definition 

endinterface : or_multi_if
// Automatically generated from VerifWorks's DVCreate-Go2UVM product
// Thanks for using VerifWorks products, see http://www.verifworks.com for more

import uvm_pkg::*;
`include "uvm_macros.svh"
// Import Go2UVM Package
import vw_go2uvm_pkg::*;
// Use the base class provided by the vw_go2uvm_pkg
class or_multi_test extends go2uvm_base_test;
  // Create a handle to the actual interface
  virtual or_multi_if vif;
  task reset;
    `uvm_info (log_id, "Start of reset", UVM_MEDIUM)
   // `uvm_info (log_id, "Fill in your reset logic here ", UVM_MEDIUM)
       this.vif.cb.reset_n <= 1'b0;
       repeat (5) @ (this.vif.cb);
       this.vif.cb.reset_n <= 1'b1;
       repeat (1) @ (this.vif.cb);
    `uvm_info (log_id, "End of reset", UVM_MEDIUM)
  endtask : reset
  task main ();
    `uvm_info (log_id, "Start of main", UVM_MEDIUM)
   // `uvm_info (log_id, "Fill in your main logic here ", UVM_MEDIUM)
	@(vif.cb);
	  begin 
	    @(vif.cb);
		vif.cb.a <= 1'b1;
		vif.cb.b <= 1'b1;
		vif.cb.c <= 1'b1;
		vif.cb.d <= 1'b1;
		vif.cb.e <= 1'b1;
	    @(vif.cb);
	    @(vif.cb);
	    @(vif.cb);
	    @(vif.cb);
		vif.cb.a <= 1'b0;
		vif.cb.b <= 1'b0;
		vif.cb.c <= 1'b0;
		vif.cb.d <= 1'b0;
		vif.cb.e <= 1'b0;
	  end

	
#300 $finish;


    `uvm_info (log_id, "End of main", UVM_MEDIUM)
  endtask : main
endclass : or_multi_test

module or_multi_go2uvm;
  timeunit 1ns;
  timeprecision 1ns;
  parameter VW_CLK_PERIOD = 10;

  // Simple clock generator
  bit clk ;
  bit clk2;
  always # (VW_CLK_PERIOD/2) clk <= ~clk;
  always # (VW_CLK_PERIOD/2) clk2 <= ~clk2;

  // Interface instance
  or_multi_if or_multi_if_0 (.*);

  // Connect TB clk to Interface instance clk

  // DUT instance
  or_multi or_multi_0 (.clk(clk),
                    .clk2(clk2),
                    .d(or_multi_if_0.d),
                    .a(or_multi_if_0.a),
                    .b(or_multi_if_0.b),
                    .c(or_multi_if_0.c),
                    .reset_n(or_multi_if_0.reset_n),
                    .e(or_multi_if_0.e));


  // Using VW_Go2UVM
  or_multi_test or_multi_test_0;
  initial begin : go2uvm_test
    or_multi_test_0 = new ();
    // Connect virtual interface to physical interface
    or_multi_test_0.vif = or_multi_if_0;
    // Kick start standard UVM phasing
    run_test ();
  end : go2uvm_test
endmodule : or_multi_go2uvm

