/********************************************
* VerifWorks Go2UVM App: VW_DVC_Go2UVM
* Automatically generated by VerifWorks's DVC_Go2UVM Riviera Apps 
* Thanks for using VerifWorks products
* Visit http://www.verifworks.com for more 
* Generated on   : 2016-06-04 15:05:51
********************************************/ 



// Generating SystemVerilog interface for module: seq_trig
// ---------------------------------------------------------
interface seq_trig_if (input logic clk);
  logic  [0:0] a;
//  logic : Signed Bit [31:0] address;
  logic  [0:0] b;
  logic  [0:0] c;
  logic  [0:0] reset_n;
  logic  [0:0] d;
//  logic : Signed Bit [31:0] data;
 // logic : Signed Bit [31:0] data1;
//  logic : Signed Bit [31:0] data2;
  logic  [0:0] e;
  logic  [0:0] parity_error;
  logic  [0:0] r;
  logic  [0:0] read;
  logic  [0:0] w;
  logic  [0:0] write;
  logic  [0:0] x;
  logic  [0:0] y;
  // End of interface signals 


  // Start of clocking block definition 
  clocking cb @(posedge clk);
    output a;
//    output address;
    output b;
    output c;
    output reset_n;
    output d;
 //   output data;
 //   output data1;
 //   output data2;
    output e;
    output parity_error;
    output r;
    output read;
    output w;
    output write;
    output x;
    output y;
  endclocking : cb
  // End of clocking block definition 

endinterface : seq_trig_if
// Automatically generated from VerifWorks's DVCreate-Go2UVM product
// Thanks for using VerifWorks products, see http://www.verifworks.com for more

import uvm_pkg::*;
`include "uvm_macros.svh"
// Import Go2UVM Package
import vw_go2uvm_pkg::*;
// Use the base class provided by the vw_go2uvm_pkg
class seq_trig_test extends go2uvm_base_test;
  // Create a handle to the actual interface
  virtual seq_trig_if vif;
  task reset;
    `uvm_info (log_id, "Start of reset", UVM_MEDIUM)
   // `uvm_info (log_id, "Fill in your reset logic here ", UVM_MEDIUM)
     this.vif.cb.reset_n <= 1'b0;
     repeat (5) @ (this.vif.cb);
     this.vif.cb.reset_n <= 1'b1;
     repeat (1) @ (this.vif.cb);
    `uvm_info (log_id, "End of reset", UVM_MEDIUM)
  endtask : reset
  task main ();
    `uvm_info (log_id, "Start of main", UVM_MEDIUM)
    `uvm_info (log_id, "Fill in your main logic here ", UVM_MEDIUM)

	@(vif.cb);
	   begin
		@(vif.cb);
		  vif.cb.a <= 1'b1;
		  vif.cb.b <= 1'b1;
		  vif.cb.c <= 1'b1;
		  vif.cb.d <= 1'b1;
		  vif.cb.e <= 1'b1;
		  vif.cb.w <= 1'b1;
		  vif.cb.r <= 1'b1;
		  vif.cb.x <= 1'b1;
		  vif.cb.y <= 1'b1;
		  vif.cb.read <= 1'b1;
		  vif.cb.write <= 1'b1;
		  vif.cb.parity_error <= 1'b1;
		@(vif.cb);
		@(vif.cb);
		@(vif.cb);
		@(vif.cb);
		@(vif.cb);
		@(vif.cb);
		  vif.cb.a <= 1'b0;
		  vif.cb.b <= 1'b0;
		  vif.cb.c <= 1'b0;
		  vif.cb.d <= 1'b0;
		  vif.cb.e <= 1'b0;
		  vif.cb.w <= 1'b0;
		  vif.cb.r <= 1'b0;
		  vif.cb.x <= 1'b0;
		  vif.cb.y <= 1'b0;
		  vif.cb.read <= 1'b0;
		  vif.cb.write <= 1'b0;
		  vif.cb.parity_error <= 1'b0;
	end
#300 $finish;


    // this.vif.cb.inp_1 <= 1'b0;
    // this.vif.cb.inp_2 <= 22;
    // repeat (5) @ (this.vif.cb);
    `uvm_info (log_id, "End of main", UVM_MEDIUM)
  endtask : main
endclass : seq_trig_test

module seq_trig_go2uvm;
  timeunit 1ns;
  timeprecision 1ns;
  parameter VW_CLK_PERIOD = 10;

  // Simple clock generator
  bit clk ;
  always # (VW_CLK_PERIOD/2) clk <= ~clk;

  // Interface instance
  seq_trig_if seq_trig_if_0 (.*);

  // Connect TB clk to Interface instance clk

  // DUT instance
  seq_trig seq_trig_0 (.clk(clk),
                    .read(seq_trig_if_0.read),
                    .reset_n(seq_trig_if_0.reset_n),
                    .write(seq_trig_if_0.write),
                    .a(seq_trig_if_0.a),
                    .b(seq_trig_if_0.b),
                    .c(seq_trig_if_0.c),
                    .d(seq_trig_if_0.d),
                    .e(seq_trig_if_0.e),
                    .r(seq_trig_if_0.r),
                    .w(seq_trig_if_0.w),
                    .x(seq_trig_if_0.x),
                    .y(seq_trig_if_0.y),
                    .parity_error(seq_trig_if_0.parity_error));


  // Using VW_Go2UVM
  seq_trig_test seq_trig_test_0;
  initial begin : go2uvm_test
    seq_trig_test_0 = new ();
    // Connect virtual interface to physical interface
    seq_trig_test_0.vif = seq_trig_if_0;
    // Kick start standard UVM phasing
    run_test ();
  end : go2uvm_test
endmodule : seq_trig_go2uvm

